[package]
edition = "2021"
name = "graphler"
version = "0.1.0"
[dependencies]
bytestring = "*"
apollo-parser = "0.4.0"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
serde_test = "1.0.144"
walkdir = "2"

