[package]
edition = "2021"
name = "graphler"
version = "0.1.0"
[dependencies]
bytestring = "*"
graphql-parser = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
graphql-tools = "0.1.0"
serde_test = "1.0.144"
walkdir = "2"

